### ISSUE TITLE
博客园商业化之路-开篇：开源的脚步，商业化的出路

### ISSUE THREAD

**Issue by cnblogs-dudu** [cnblogs/open-business#1]
今年是园子能否找到商业化出路的决定性一年，这是一场破釜沉舟的决战，这是一个山穷水尽疑无路的巨大挑战。

在当前一穷二白三无人脉的困境下，这场决战，这个挑战，更是难上加难。

能否在园子里找到足够的支持、帮助与合作力量，商业模式是否能够与用户实现双赢，是破局的关键。

我们计划这个季度启动园子的新一轮天使融资，在启动融资之前，我们产生了一个想法。

我们相信用户的力量。园子能发展到现在就是来自用户的支持，几个关键发展节点都离不开用户的重要作用。记忆犹新的是2012年当时也是极度困难，服务器硬件坏了却没钱买服务器，有用户建议我们上阿里云，我们听取了用户的建议，并最终因此拯救了困境中的园子（因为上云带来的新机会）。

我们相信开源的力量。2004年刚创建园子的时候，用的就是一款开源软件 .Text，然后修修补补很多年，如果没有这款开源软件，当时园子网站根本搭建不起来。而现在更是离不开开源，园子的网站部署在开源的 Kubernetes 上，我们用开源的 .NET 和 Angular 开发着园子的产品。

结合用户与开源的力量，我们想到把园子的商业化作为一个开源项目，以开放共赢的方式和大家共同探索园子的商业化出路，于是就有了这篇“开源的脚步，商业化的出路”。

这个另类的开源项目已经托管在github上，项目名称是 OpenBusiness，仓库地址：https://github.com/cnblogs/open-business

期待您关注这个开源项目，期待您关注、助力、参与园子的商业化过程，我们相信为开发者而存在的园子，在大家的支持下一定能找到一种与开发者共赢的商业模式，从而柳暗花明又一春。

原文链接：https://www.cnblogs.com/cmt/p/18133891

**Comment by blurhead** [comment]
支持

**Comment by chidafy** [comment]
加油

**Comment by seven1240** [comment]
+1

**Comment by zaimatest** [comment]
支持一下吧

**Comment by 2424004764** [comment]
支持

**Comment by hi-nikola** [comment]
支持

**Comment by liuweiisme** [comment]
支持

**Comment by lv997** [comment]
持续关注，支持。

**Comment by njtuiwang** [comment]
先支持
