### ISSUE TITLE
众包平台 v0.1.0

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/open-business#13]

**Comment by CG-Lin** [comment]
![ce79b81e1a88f6fc77d510b95c2059b](https://github.com/cnblogs/open-business/assets/64123663/17fcf459-3f0d-4d6b-8a9a-0ab9ee4b9d1b)

**Comment by cnblogs-team** [comment]
定位：是开发任务的众包，不是开发项目的外包

**Comment by cnblogs-team** [comment]
是软件开发过程中各种细分工作的众包

**Comment by lv997** [comment]
细致化到了任务，那势必会有高级程序员或者是架构师的存在，才能够把项目需求拆解成可以量化的任务做分发。园园是不是要找到这样的大佬会更加的困难呢。

**Comment by cnblogs-team** [comment]
小任务小交付小金额

**Comment by cnblogs-team** [comment]
已经在以众包平台商业模式融资 #30
