### ISSUE TITLE
博客园商业化之路-商业模式：帮助开发者用代码改变口袋

### ISSUE THREAD

**Issue by cnblogs-team** [cnblogs/open-business#19]
二十年来，由于一直没有找到商业模式，园子不是长大的，是亏大的，漫漫二十年只有3年左右是挣钱的，其他时间都是亏；这二十年，园子不是发展起来的，是挣扎起来的，经历了好几次起死回生。

在熬过三年危机后，现在到了不找到商业模式就活不下的穷困潦倒地步，之前在商业化上碌碌无为现在到了无路可退。

去年我们尝试了付费会员的模式，今年第一季度我们思考了在AI方向上的突破口，今年第二季度在准备启动融资之前，我们抛弃了之前的思维框框重新对商业模式进行思考，并决定以开源的方式在园子里与大家一起探讨，于是有了上一篇博文 —— [开源的脚步，商业化的出路](https://www.cnblogs.com/cmt/p/18133891)。

结合之前的思考与开源后与大家的探讨，我们更加明确了与开发者共赢的商业化方向，基于园子的 slogan —— 「帮助开发者用代码改变世界」，我们想到了用一句话来表达 —— 「帮助开发者用代码改变口袋」，园子的商业化一定要在帮助开发者挣钱这条路上找突破口，园子的商业模式就是从开发者鼓起来的口袋里分一点。

在发布上篇博文之前，我们考虑的是做一个D2D(Developer to Developer)的交易平台，但没有想好交易什么。发布博文后，好几位园友建议做软件开发众包平台，这个模式我们早就考虑过，有几个技术社区已经做过，存在交易过程复杂、难以标准化、项目需求方与开发者之间的预期相差很大、前期运营投入大等问题，一开始我们看到这个建议时直摇头，现在这个阶段打死也不敢做这个模式。

后来一位园友的[评论](https://www.cnblogs.com/cmt/p/18133891#5266544)动摇了我们对众包模式的固有偏见。

> 众包平台不考虑下吗，全是程序员；程序员只会写程序啊

对啊，园子里的用户最擅长的就是写代码，如果让他们多花点时间写代码就能挣钱，那岂不就是最简单最容易规模化的模式？如果不是写代码的方式，那就需要让他们录个课，写个教程，直播带个货，卖点东西，做个软件产品…，任何一个门槛都会让很多开发者望而却步。

再联想到滴滴的模式，利用上下班开车时间顺带一下客就能挣点钱，这多简单，这样的交易，越简单越容易成交。

于是想到可以将难以落地的复杂模式简单化，抛开基于项目或者产品外包开发的传统众包模式，走一条让开发者基于自己已有的代码能力利用空余时间挣钱的轻量级众包模式，比如将具体开发任务中的某个开发事项众包，比如将开发中遇到的一个具体技术问题众包，比如将一个众包任务的完成时间控制在8小时以内...，也许可以走出一条与众不同的众包之路，让我们在帮助开发者用代码改变世界的同时，帮助开发者用代码改变口袋，从而让园子跃上新台阶。

这是我们关于园子商业模式的最新思考，与大家分享，欢迎探讨与吐槽。

我们会继续进一步思考，如果找不到比这更好的商业模式，会基于这个商业模式准备商业计划，然后开始融资。

如果您有兴趣与我们探讨园子商业化过程中的合作机会，欢迎加[企业微信](https://www.cnblogs.com/cmt/articles/17677736.html)与我们联系。

原文链接：https://www.cnblogs.com/cmt/p/18148611

**Comment by cnblogs-team** [comment]
公众号留言精选：

> Golden Snitch：不知道其他众包平台现在运营得怎么样，我感觉对大多数程序员来说还是很难接到活的。一个项目发布后往往很多人去竞争，而最终项目方只会选择一个人，这就导致只有少数人能挣钱。如果能改变这种项目整个外包的模式，所有在平台发布的项目需求必须做任务拆分，每个任务都是尽可能小的拆分(甚至可以是完成一个函数、方法的编写，或者完成另外一个任务的单元测试编写)，很明确而且可以完成标准可以量化的，让更多的人能够接到任务，获得受益，即使单个任务的收益并不高，但只要能让更多的人都参与进来，项目的开发效率，交付质量，还有程序员的积极性可能都会有很大的提升。

> 哥白尼：这个思路不错，但是集成测试和最终交付就必须做好。那基于这个思路，是不是可以有“审计员”这么个角色，也就是通过认证有能力来评判最终交付的一批人，他们当中有80%认为达到目标就算交付。大家共同承担所有责任。

**Comment by dydhyhwu** [comment]
个人感觉国内技术社区的一些痛点：
1. 园子里以前精品内容相对其他社区是居多的，但是整体还是数量较少，频率较低，方向比较发散，可是现在也出现了好多复制的文章，或者完全是流水日记的技术文章。（不少社区都是一样的问题，导致开发者习惯`Google`，而不是国内搜索，因为给大家的反馈就是：“高质量有深度，能解决实际问题，成体系的知识太少”）
2. 技术风向、最新前沿等内容较少，用户更多的选择`Google`之类的。

想法：
1. 园子官方入场组织，针对不同用户群体建立优质、完善、最新的知识体系（比如各类语言的教程**以及落地demo/project**，并将相关内容的精品文章关联过来，让园子内的内容关联度提高，减少知识的碎片化），同时也激励贡献者，可以前期做流量引导，积分商城，等等，取决于钱包。**但是前期可能审核工作量会比较大**
2. 紧跟技术前沿，发布技术前沿信息，论文，技术成果等。比如`AI`较火时，官方通过*第一个想法*将精品内容关联，聚合起来，让园子里的开发者都有强烈的兴趣参与进来。而不只是*听过*、*体验过*，实际上知之甚浅，技术氛围也就起不来。这里也可以把大佬们和有想法的作者们聚集起来。
3. 首页根据1，2进行调整，聚焦高聚合度的精品内容和前沿动态。
4. 可以通过活动的方式引入赞助，比如征文活动，知识库共建计划，xx框架/语言/领域实战共建计划（比如`Tauri 全平台应用构建实战/难点/创新点`），*商业不太懂，完全就是拍脑袋想的，勿怪*

希望园子越来越好。

*PS：现在想找一些相关的技术实践，成体系的学习知识，要么就是很浅显的文档翻译还翻译不全，要么就是一个真正的demo，导致大家抄来抄去的也不知其所以然，反正大家都这么写。要么只能去看相关技术的原始文档， 要么翻源码，或者翻下`issue`。国内不是抄来抄去的内容， 就是AI自动生成的一些奇奇怪怪的幻觉文章*

**Comment by cnblogs-team** [comment]
博文评论精选：
> 铁打接班人流水打工人：建议交易完成度控制放在第三方（平台）那里，这个可以是突破点，毕竟不能只听听甲方还是乙方的片面之词

**Comment by cnblogs-team** [comment]
博文评论精选：
> kiba518: 干众包吧，我以前在猪八戒和一品威客接活，现在这俩平台都不用了，因为现在在那些平台，自由开发者根本接不到任务，全是工作室。相当于他们已经放弃了自由开发者了。这是一个相当庞大的群体，如果博客园能接手过来，那还是非常可观的。

**Comment by cnblogs-team** [comment]
博文评论精选：
> 不语：很多时候遇到一些工作问题，自己花点时间也能解决，但如果有一个快速的付费解决渠道我也愿意付费解决的。例如有一个新需求需要用到WEB 3D相关的技术,在这以前从未接触过这方面的东西，这时候需要调研方案，这其中有很多方案可以选，但因为没经验不确定那个更符合自己的需求场景，这时候可能就要花一两天的时间把每个方案都简单调研一下搞个demo看效果。如果这时候有个渠道能够快速找到有经验的人提供指导是能够少走很多弯路降低成本的，而提供服务的人可能只是某个有这方经验的普通开发在工作至于分享了下经验而获得了一笔小小的收入

**Comment by xinguankeli** [comment]
一定要走社会两元店的路线，59、99等固定额度，现在的开发者自大的很多，上来就要加2000、3000、5000，搞得双方都感觉做不下去

**Comment by zhhaojie** [comment]
是的，我们不想改变世界，我们只是改变口袋。 如果在让世界变得更加美好的同时，又改变了口袋。这是最好的结局。
