### ISSUE TITLE
借鸡生蛋，一堆程序员，直接开个外包板块，搞抽成不就行了

### ISSUE THREAD

**Issue by CG-Lin** [cnblogs/open-business#3]

**Comment by LinuxZilong** [comment]
好主意

**Comment by hi-nikola** [comment]
外包 求职 远程工作 知识付费 。能赚到钱就会有人来。

**Comment by cnblogs-team** [comment]
在考虑如果众包平台，一开始如何切入？

**Comment by gundamff** [comment]
共享员工

**Comment by CG-Lin** [comment]
> 在考虑如果做众包平台，一开始如何切入？

实施步骤的大致框架昨天已经和你们运营企业微信的同事聊过了，至于你这个切入是指什么？怎么拿到项目还是怎么搭起这个平台？

**Comment by cnblogs-team** [comment]
@CG-Lin 您好，昨天已经在微信探讨的一部分就属于切入点——「起步阶段可以由园子出面接项目，然后众包给园子里的用户」，就是开始阶段如何以可行的方式以最低成本完成第一个众包项目

**Comment by CG-Lin** [comment]
> @CG-Lin 您好，昨天已经在微信探讨的一部分就属于切入点——「起步阶段可以由园子出面接项目，然后众包给园子里的用户」，就是开始阶段如何以可行的方式以最低成本完成第一个众包项目
如果这个“低成本”是为了更好地拿项目，其实很简单，你们完全可以在首页置顶或则会员群以“合作人”身份招募第一批参与众包的园子里的程序员。像Seata社区一样开一个“高度合作人”的有效认证榜单，具体怎么操作有兴趣再详谈，总之就是让第一批愿意参与的人愿意以只收取极低的价格换取以“合作者”的身份协助园子完成这一次商业转型（希望拿出最大的诚意，而不是简单的给用户续个99会员，毕竟园子会员现在本身没有什么很实用的价值，后续怎么提升会员实用价值昨天也和你们微信讨论过了）。只有等园子众包平台做起来，后续再参与园子众包项目的那就按正常的市场定价，和园子也只是”介绍人和被介绍人“的雇佣关系。
说一句比较现实的话，如果低成本只是指园子既想第一次众包项目让大家”为爱发电“基本不可能，既然园子目前资金困难，既想靠价格战多拿项目，又想保质保量，然后园子自己能赚一点，那就用可能实现的”未来“让一部分前期愿意减少自己利益的人加入，没有诱惑力就没有束缚力，不然人家完全可以做到一半就跑。

**Comment by cnblogs-team** [comment]
@CG-Lin 您好，众包给园子里的开发者不存在“低成本”问题，这是分成模式，是从项目需求方给开发者的费用中分成，给开发者的费用越高，我们拿到的分成就越多。

可能是「起步阶段可以由园子出面接项目，然后众包给园子里的用户」让你产生了误解，经过进一步考虑，「由园子出面接项目」这种方式不打算采用。

**Comment by CG-Lin** [comment]
> @CG-Lin 您好，众包给园子里的开发者不存在“低成本”问题，这是分成模式，是从项目需求方给开发者的费用中分成，给开发者的费用越高，我们拿到的分成就越多。
> 
> 可能是「起步阶段可以由园子出面接项目，然后众包给园子里的用户」让你产生了误解，经过进一步考虑，「由园子出面接项目」这种方式不打算采用。

有几个问题需要你们运营思考下，我先不管你们打不打算做，不论是园子评论区还是github议题，很多人无非就是让你们开设卖课，付费资源等板块。但简单做个市场分析就知道，园子大部分流量来源小白在现在浏览器搜索某某问题然后进来找解决问题的博客的，用户习惯就是看完解决博客就退出。这种比较流动的用户想让他们花时间去“发现”你们园内新出现的功能板块并且付费，我个人认为并不可靠。
在没有投资者的情况下给你们提供“财力”资源的情况下，你们唯一能使用的就只有已有粘性的用户，这些用户愿意花精力去看你们洋洋洒洒的“求助博客”，愿意去看你们衬衫设计图。更直白一点，园子也就目前这些“人力”资源以及姑且算得上技术论坛“头部”的影响力能够使用（我不清楚你们老板有没有人脉），不论是任务众包还是项目外包，说白了都是前面两者资源能够发挥最大作为的办法（打算直接把园子套现了除外）。
某种意义上说园子自由社区是成熟的，但商业确实一片空白。而商业化的起点应当是由你们牵头去做某一些事，而不是像上文说的妄图开设一些板块让指望用户自己参与进来。只有你们一个领域运作成熟了才能到开设一个“板块”，这个时候网站运营才能说完全成为“第三方”。

**Comment by CG-Lin** [comment]
> @CG-Lin 您好，众包给园子里的开发者不存在“低成本”问题，这是分成模式，是从项目需求方给开发者的费用中分成，给开发者的费用越高，我们拿到的分成就越多。
> 
> 可能是「起步阶段可以由园子出面接项目，然后众包给园子里的用户」让你产生了误解，经过进一步考虑，「由园子出面接项目」这种方式不打算采用。

有几个问题需要你们运营思考下，我先不管你们打不打算做，不论是园子评论区还是github议题，很多人无非就是让你们开设卖课，付费资源等板块。但简单做个市场分析就知道，园子大部分流量来源小白先在浏览器搜索某某问题然后进来找解决问题的博客的，用户习惯就是看完解决博客就退出。这种比较流动的用户想让他们花时间去“发现”你们园内新出现的功能板块并且付费，我个人认为并不可靠。
在没有投资者给你们提供“财力”资源的情况下，你们唯一能使用的就只有已有粘性的用户，这些用户愿意花精力去看你们洋洋洒洒的“求助博客”，愿意去看你们衬衫设计图。更直白一点，园子也就目前这些“人力”资源以及姑且算得上技术论坛“头部”的影响力能够使用（我不清楚你们老板有没有人脉），不论是任务众包还是项目外包，说白了都是前面两者资源能够发挥最大作为的办法（打算直接把园子套现了除外）。
某种意义上说园子自由社区是成熟的，但商业确实一片空白。而商业化的起点应当是由你们牵头去做某一些事，而不是像上文说的妄图开设一些板块让指望用户自己参与进来。只有你们一个领域运作成熟了才能到开设一个“板块”，这个时候才是仅作为搭建交易平台的“第三方”的角色。

**Comment by efmingliu** [comment]
> > @CG-Lin 您好，昨天已经在微信探讨的一部分就属于切入点——「起步阶段可以由园子出面接项目，然后众包给园子里的用户」，就是开始阶段如何以可行的方式以最低成本完成第一个众包项目
> 
> 如果这个“低成本”是为了更好地拿项目，其实很简单，你们完全可以在首页置顶或则会员群以“合作人”身份招募第一批参与众包的园子里的程序员。像Seata社区一样开一个“高度合作人”的有效认证榜单，具体怎么操作有兴趣再详谈，总之就是让第一批愿意参与的人愿意以只收取极低的价格换取以“合作者”的身份协助园子完成这一次商业转型（希望拿出最大的诚意，而不是简单的给用户续个99会员，毕竟园子会员现在本身没有什么很实用的价值，后续怎么提升会员实用价值昨天也和你们微信讨论过了）。只有等园子众包平台做起来，后续再参与园子众包项目的那就按正常的市场定价，和园子也只是”介绍人和被介绍人“的雇佣关系。 说一句比较现实的话，如果低成本只是指园子既想第一次众包项目让大家”为爱发电“基本不可能，既然园子目前资金困难，既想靠价格战多拿项目，又想保质保量，然后园子自己能赚一点，那就用可能实现的”未来“让一部分前期愿意减少自己利益的人加入，没有诱惑力就没有束缚力，不然人家完全可以做到一半就跑。

参照修庙塑佛，最好把施主的名字搞个功德榜。毕竟钱给不了，还不能给个名嘛

**Comment by devilmaycry812839668** [comment]
@cnblogs-team 有没有考虑弄个招聘网站那种的样子

**Comment by devilmaycry812839668** [comment]
@cnblogs-team 不行就搞搞二手交易平台，比如卖技术类书籍，二手的，专门提供二手技术类书籍买卖的平台呢，这点咸鱼就不太行

**Comment by devilmaycry812839668** [comment]
@cnblogs-team 再不行就搞搞直播，比如弄个技术直播，每周都找几个技术大佬讲技术和项目代码啥的，这样也好拉拉人气，然后再搞各种其他的赚钱的东西

**Comment by cnblogs-team** [comment]
@CG-Lin 非常感谢您的建议！

**Comment by zhhaojie** [comment]
> > @CG-Lin 您好，众包给园子里的开发者不存在“低成本”问题，这是分成模式，是从项目需求方给开发者的费用中分成，给开发者的费用越高，我们拿到的分成就越多。
> > 可能是「起步阶段可以由园子出面接项目，然后众包给园子里的用户」让你产生了误解，经过进一步考虑，「由园子出面接项目」这种方式不打算采用。
> 
> 有几个问题需要你们运营思考下，我先不管你们打不打算做，不论是园子评论区还是github议题，很多人无非就是让你们开设卖课，付费资源等板块。但简单做个市场分析就知道，园子大部分流量来源有技术问题的用户先在浏览器搜索某某问题然后进来找解决问题的博客的，用户习惯就是看完解决博客就退出。这种比较流动的用户想让他们花时间去“发现”你们园内新出现的功能板块并且付费，我个人认为并不可靠。你们也没有钱也没有渠道去宣发你们最新开设的商业板块（据我本人观察博客园在各视频平台或社交平台没有具备规模的账户），如果你们有App还能借助更新公告短期小范围宣传，但目前仅止步于的Web中，也就只能依赖“公告”让有心关注你们的用户看到，条件实在过于苛刻。 在没有投资者给你们提供“财力”资源的情况下，你们唯一能使用的就只有已有粘性的用户，这些用户愿意花精力去看你们洋洋洒洒的“求助博客”，愿意去看你们衬衫设计图。更直白一点，园子也就目前这些“人力”资源以及姑且算得上技术论坛“头部”的影响力能够使用（我不清楚你们老板有没有人脉），不论是任务众包还是项目外包，说白了都是前面两者资源能够发挥最大作为的办法（打算直接把园子套现了除外）。 某种意义上说园子自由社区是成熟的，但商业领域的知名度一片空白（比如知识星球被人所知的商业领域就是付费课程）。而商业化的起点应当是由你们牵头去做某一些事，而不是像上文说的妄图开设一些板块把主动性交给用户，期望他们能自觉参与进来。还是以知识星球举例，他们初期是自己做课程做自媒体打出知名度，然后再推出App把观众变成用户，平台的创作者这一角色也由平台的工作人员转变为广大的用户创作者。只有你们一个领域运作成熟了才能到开设一个“板块”，这个时候才是仅作为搭建交易平台的“第三方”的角色。

解释得非常深入。因为来博客园的人，要么是来学习，找问题解决方案。要么是把经验分享出来，记录一下。这些人，要么是在工作岗位上的，要么就是离职的了，想继续学习的，想赚钱门路的。任何一个东西能够赚钱，一定是有钱可以赚。都是利益。

**Comment by cnblogs-team** [comment]
已经在以众包平台商业模式融资 #30
